<?php

use \Illuminate\Database\Seeder;

class PermissionsSeeder extends Seeder
{
    public function run()
    {
        App\Models\Permission::create([
            'identification' => '/system',
            'title'          => '系统管理',
            'icon'           => 'system',
            'component'      => '',
            'redirect'       => '/system/admin',
            'description'    => '系统管理',
            'type'           => 0,
            'sort'           => 0,
            'status'         => 1,
            'display'        => 1,
            'create_time'    => time(),
            'children'       => [
                [
                    'identification' => '/system/admin',
                    'title'          => '用户管理',
                    'icon'           => 'admin',
                    'component'      => 'admin',
                    'redirect'       => '',
                    'description'    => '用户管理',
                    'type'           => 0,
                    'sort'           => 0,
                    'status'         => 1,
                    'display'        => 1,
                    'create_time'    => time(),
                ],
                [
                    'identification' => '/system/role',
                    'title'          => '角色管理',
                    'icon'           => 'role',
                    'component'      => 'role',
                    'redirect'       => '',
                    'description'    => '角色管理',
                    'type'           => 0,
                    'sort'           => 1,
                    'status'         => 1,
                    'display'        => 1,
                    'create_time'    => time(),
                ],
                [
                    'identification' => '/system/permission',
                    'title'          => '权限管理',
                    'icon'           => 'permission',
                    'component'      => 'permission',
                    'redirect'       => '',
                    'description'    => '权限管理',
                    'type'           => 0,
                    'sort'           => 2,
                    'status'         => 1,
                    'display'        => 1,
                    'create_time'    => time(),
                ],
            ]
        ]);

        App\Models\Permission::create([
            'identification' => '/api/admins',
            'title'          => '管理员列表',
            'icon'           => '',
            'component'      => '',
            'redirect'       => '',
            'description'    => '管理员列表',
            'type'           => 1,
            'status'         => 1,
            'create_time'    => time(),
            'children'       => [
                [
                    'identification' => '/api/admins/create',
                    'title'          => '创建用户',
                    'icon'           => '',
                    'component'      => '',
                    'redirect'       => '',
                    'description'    => '创建用户',
                    'type'           => 1,
                    'status'         => 1,
                    'create_time'    => time(),
                ],
                [
                    'identification' => '/api/admins/update',
                    'title'          => '更新用户',
                    'icon'           => '',
                    'component'      => '',
                    'redirect'       => '',
                    'description'    => '更新用户',
                    'type'           => 1,
                    'status'         => 1,
                    'create_time'    => time(),
                ],
                [
                    'identification' => '/api/admins/delete',
                    'title'          => '删除用户',
                    'icon'           => '',
                    'component'      => '',
                    'redirect'       => '',
                    'description'    => '删除用户',
                    'type'           => 1,
                    'status'         => 1,
                    'create_time'    => time(),
                ],
                [
                    'identification' => '/api/admins/edit',
                    'title'          => '编辑用户',
                    'icon'           => '',
                    'component'      => '',
                    'redirect'       => '',
                    'description'    => '编辑用户',
                    'type'           => 1,
                    'status'         => 1,
                    'create_time'    => time(),
                ],
                [
                    'identification' => '/api/admins/upload',
                    'title'          => '用户头像上传',
                    'icon'           => '',
                    'component'      => '',
                    'redirect'       => '',
                    'description'    => '用户头像上传',
                    'type'           => 1,
                    'status'         => 1,
                    'create_time'    => time(),
                ],
                [
                    'identification' => '/api/admins/roles',
                    'title'          => '管理员角色选择列表',
                    'icon'           => '',
                    'component'      => '',
                    'redirect'       => '',
                    'description'    => '管理员角色选择列表',
                    'type'           => 1,
                    'status'         => 1,
                    'create_time'    => time(),
                ],
            ]
        ]);
        App\Models\Permission::create([
            'identification' => '/api/roles',
            'title'          => '角色列表',
            'icon'           => '',
            'component'      => '',
            'redirect'       => '',
            'description'    => '角色列表',
            'type'           => 1,
            'status'         => 1,
            'create_time'    => time(),
            'children'       => [
                [
                    'identification' => '/api/roles/create',
                    'title'          => '创建角色',
                    'icon'           => '',
                    'component'      => '',
                    'redirect'       => '',
                    'description'    => '创建角色',
                    'type'           => 1,
                    'status'         => 1,
                    'create_time'    => time(),
                ],
                [
                    'identification' => '/api/roles/update',
                    'title'          => '更新角色',
                    'icon'           => '',
                    'component'      => '',
                    'redirect'       => '',
                    'description'    => '更新角色',
                    'type'           => 1,
                    'status'         => 1,
                    'create_time'    => time(),
                ],
                [
                    'identification' => '/api/roles/delete',
                    'title'          => '删除角色',
                    'icon'           => '',
                    'component'      => '',
                    'redirect'       => '',
                    'description'    => '删除角色',
                    'type'           => 1,
                    'status'         => 1,
                    'create_time'    => time(),
                ],
                [
                    'identification' => '/api/roles/edit',
                    'title'          => '编辑角色',
                    'icon'           => '',
                    'component'      => '',
                    'redirect'       => '',
                    'description'    => '编辑角色',
                    'type'           => 1,
                    'status'         => 1,
                    'create_time'    => time(),
                ],
                [
                    'identification' => '/api/roles/permissions',
                    'title'          => '角色权限选择列表',
                    'icon'           => '',
                    'component'      => '',
                    'redirect'       => '',
                    'description'    => '角色权限选择列表',
                    'type'           => 1,
                    'status'         => 1,
                    'create_time'    => time(),
                ],
            ]
        ]);
        App\Models\Permission::create([
            'identification' => '/api/permissions',
            'title'          => '权限列表',
            'icon'           => '',
            'component'      => '',
            'redirect'       => '',
            'description'    => '权限列表',
            'type'           => 1,
            'status'         => 1,
            'create_time'    => time(),
            'children'       => [
                [
                    'identification' => '/api/permissions/create',
                    'title'          => '创建权限',
                    'icon'           => '',
                    'component'      => '',
                    'redirect'       => '',
                    'description'    => '创建权限',
                    'type'           => 1,
                    'status'         => 1,
                    'create_time'    => time(),
                ],
                [
                    'identification' => '/api/permissions/update',
                    'title'          => '更新权限',
                    'icon'           => '',
                    'component'      => '',
                    'redirect'       => '',
                    'description'    => '更新权限',
                    'type'           => 1,
                    'status'         => 1,
                    'create_time'    => time(),
                ],
                [
                    'identification' => '/api/permissions/delete',
                    'title'          => '删除权限',
                    'icon'           => '',
                    'component'      => '',
                    'redirect'       => '',
                    'description'    => '删除权限',
                    'type'           => 1,
                    'status'         => 1,
                    'create_time'    => time(),
                ],
                [
                    'identification' => '/api/permissions/edit',
                    'title'          => '编辑权限',
                    'icon'           => '',
                    'component'      => '',
                    'redirect'       => '',
                    'description'    => '编辑权限',
                    'type'           => 1,
                    'status'         => 1,
                    'create_time'    => time(),
                ],
                [
                    'identification' => '/api/permissions/trees',
                    'title'          => '上级权限选择树状列表',
                    'icon'           => '',
                    'component'      => '',
                    'redirect'       => '',
                    'description'    => '上级权限选择树状列表',
                    'type'           => 1,
                    'status'         => 1,
                    'create_time'    => time(),
                ],
            ]
        ]);
    }
}
